[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 460800
build_unflags =
  -std=gnu++11
build_flags =
  -std=gnu++17
  -DCORE_DEBUG_LEVEL=0
lib_deps =
  marcoschwartz/LiquidCrystal_I2C@1.1.4
  z3t0/IRremote@4.4.1
